#!/usr/bin/env python3
"""Build a browsable Markdown catalog from the Open Problems in OR JSONL."""

from __future__ import annotations

import argparse
import json
import os
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


DEFAULT_INPUT = Path(
    "datasets/open_problems_in_or/mathematics_of_operations_research.jsonl"
)
DEFAULT_OUTPUT = Path(
    "datasets/open_problems_in_or/mathematics_of_operations_research_index.md"
)
SOURCE_SITE = "https://pranav-nuti.github.io/open-problems-in-or/"
REQUIRED_FIELDS = (
    "problem_id",
    "title",
    "problem_definition_latex",
    "source_paper_journal",
    "source_paper_title",
    "source_paper_publication_year",
    "website_url",
    "data_url",
)


class CatalogError(RuntimeError):
    """Raised when the snapshot cannot be validated or rendered."""


def load_records(path: Path) -> list[dict[str, Any]]:
    """Load JSONL while validating IDs and the fields used by the catalog."""

    records: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise CatalogError(f"{path}:{line_number}: invalid JSON: {exc}") from exc
            if not isinstance(record, dict):
                raise CatalogError(f"{path}:{line_number}: expected a JSON object")
            missing = [field for field in REQUIRED_FIELDS if record.get(field) in (None, "")]
            if missing:
                raise CatalogError(
                    f"{path}:{line_number}: missing required fields: {', '.join(missing)}"
                )
            problem_id = str(record["problem_id"])
            if problem_id in seen_ids:
                raise CatalogError(f"{path}:{line_number}: duplicate ID {problem_id}")
            seen_ids.add(problem_id)
            records.append(record)
    if not records:
        raise CatalogError(f"{path}: snapshot is empty")
    return records


def _cell(value: Any) -> str:
    return " ".join(str(value or "").split()).replace("|", r"\|")


def _link(label: Any, url: Any) -> str:
    safe_label = _cell(label).replace("]", r"\]")
    safe_url = str(url or "").strip()
    return f"[{safe_label}]({safe_url})" if safe_url else safe_label


def _progress(record: Mapping[str, Any]) -> str:
    progress = record.get("solution_progress")
    if not isinstance(progress, dict):
        return "None listed"
    solutions = progress.get("solutions")
    partial = progress.get("partial_progress")
    solution_count = len(solutions) if isinstance(solutions, list) else 0
    partial_count = len(partial) if isinstance(partial, list) else 0
    labels: list[str] = []
    if solution_count:
        labels.append(f"{solution_count} solution")
    if partial_count:
        labels.append(f"{partial_count} partial")
    return ", ".join(labels) if labels else "None listed"


def render_catalog(records: Sequence[Mapping[str, Any]]) -> str:
    """Render records grouped by source-paper publication year."""

    by_year: dict[int, list[Mapping[str, Any]]] = defaultdict(list)
    for record in records:
        by_year[int(record["source_paper_publication_year"])].append(record)

    area_counts = Counter(str(record.get("area") or "Unspecified") for record in records)
    solution_count = sum(
        1
        for record in records
        if isinstance(record.get("solution_progress"), dict)
        and record["solution_progress"].get("solutions")
    )
    partial_count = sum(
        1
        for record in records
        if isinstance(record.get("solution_progress"), dict)
        and record["solution_progress"].get("partial_progress")
    )
    all_unverified = all(bool(record.get("unverified")) for record in records)

    lines = [
        "<!-- Generated by scripts/build_open_problems_in_or_index.py. -->",
        "",
        "# Mathematics of Operations Research: imported open problems",
        "",
        (
            f"This catalog contains **{len(records)}** records imported from "
            f"[Open Problems in Operations Research]({SOURCE_SITE})."
        ),
        "",
        (
            "**Verification warning:** the upstream entries are marked as "
            + ("unverified" if all_unverified else "not uniformly verified")
            + " and should not be treated as independently confirmed open problems."
        ),
        "",
        (
            f"Coverage: {len(by_year)} publication years and {len(area_counts)} "
            f"area labels. {solution_count} records list a solution and "
            f"{partial_count} list partial progress; these sets may overlap."
        ),
        "",
        (
            "Machine-readable snapshot: "
            "[mathematics_of_operations_research.jsonl]"
            "(mathematics_of_operations_research.jsonl)."
        ),
        "",
    ]

    for year in sorted(by_year, reverse=True):
        year_records = sorted(
            by_year[year],
            key=lambda record: (
                int(record.get("number") or 0),
                str(record["problem_id"]),
            ),
        )
        lines.extend(
            [
                f"## {year} ({len(year_records)})",
                "",
                "| Source no. | Problem ID | Open problem | Area | Source paper | Progress |",
                "|---:|---|---|---|---|---|",
            ]
        )
        for record in year_records:
            source_paper = _link(
                record["source_paper_title"],
                record.get("source_paper_url"),
            )
            problem = _link(record["title"], record["website_url"])
            lines.append(
                "| "
                + " | ".join(
                    (
                        _cell(record.get("number")),
                        f"`{_cell(record['problem_id'])}`",
                        problem,
                        _cell(record.get("area") or "Unspecified"),
                        source_paper,
                        _progress(record),
                    )
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines)


def write_text_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        records = load_records(args.input)
        write_text_atomic(args.output, render_catalog(records))
    except (CatalogError, OSError) as exc:
        print(f"error: {exc}")
        return 1
    print(f"Wrote {len(records)} catalog entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
